development:
  adapter: postgresql
  encoding: utf8
  database: chat_app_dev
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: chat_app_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: chat_app_prod
  pool: 5
  username:
  password:
